<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">matchStrings</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCglTdHJpbmcJcGFyZW50U3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJwYXJlbnRTdHJpbmciICk7DQoJU3RyaW5nCXN1YnN0cmluZyA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAic3Vic3RyaW5nIiApOw0KCVN0cmluZwl1
c2VSZWdleCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAidXNlUmVnZXgi
ICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQpib29sZWFuIG1hdGNoZXMgPSBmYWxzZTsN
CmlmKHVzZVJlZ2V4PT0idHJ1ZSIpew0KCW1hdGNoZXMgPSBwYXJlbnRTdHJpbmcubWF0Y2hlcyhz
dWJzdHJpbmcpOw0KfWVsc2V7DQoJbWF0Y2hlcyA9IHBhcmVudFN0cmluZy5tYXRjaGVzKCIoLiop
IitzdWJzdHJpbmcrIiguKikiKTsNCn0NCg0KDQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlw
ZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlw
ZWxpbmVDdXJzb3JfMSwgIm1hdGNoZXMiLCBTdHJpbmcudmFsdWVPZihtYXRjaGVzKSApOw0KcGlw
ZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7DQo=</value>
</Values>
