filebeat.prospectors:
  - type: log
    enabled: true
    paths:
      - ${SERVER_LOGFILE_PATH}
    exclude_lines: ['D] ','T] ']
    encoding: utf-8
    fields_under_root: true
    fields:
      log_identifier: server_log
    multiline:
      pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}
      match: after
      negate: true
  - type: log
    enabled: true
    paths:
      - ${WRAPPER_LOGFILE_PATH}
    exclude_lines: ^.*\|.*\|.*\|[[:space:]]*$
    encoding: utf-8
    fields_under_root: true
    fields:
      log_identifier: wrapper_log
    multiline:
      pattern: ^.*\|.*\|.*\| 	at.*
      match: after
      negate: false

processors:
- add_locale:
    format: abbreviation

fields:
  env: ${SERVER_ID}

output.logstash:
  # The Logstash hosts
  hosts: [ "${LOGSTASH_HOST}:${LOGSTASH_PORT}" ]
